In [38]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle
tf.__version__

'2.12.0'

In [2]:
df_dolar_brl = pd.read_csv("H:/Barbosa/Downloads/Month.csv", index_col=False)

In [3]:
df_dolar_brl

Date    Last  Opening     Max     Min
0    01/08/20  5.5567   5.2223  5.6722  5.2131
1    01/07/20  5.2242   5.4660  5.4763  5.0827
2    01/06/20  5.4672   5.3340  5.5082  4.8175
3    01/05/20  5.3370   5.4861  5.9718  5.2691
4    01/04/20  5.4875   5.2252  5.7484  5.0487
..        ...     ...      ...     ...     ...
327  01/05/93  0.0152   0.0152  0.0152  0.0152
328  01/04/93  0.0117   0.0117  0.0117  0.0117
329  01/03/93  0.0103   0.0103  0.0103  0.0103
330  01/02/93  0.0079   0.0079  0.0079  0.0079
331  01/01/93  0.0060   0.0060  0.0060  0.0060

[332 rows x 5 columns]

In [4]:
date_array = np.array(df_dolar_brl["Date"])
date_array

array(['01/08/20', '01/07/20', '01/06/20', '01/05/20', '01/04/20',
       '01/03/20', '01/02/20', '01/01/20', '01/12/19', '01/11/19',
       '01/10/19', '01/09/19', '01/08/19', '01/07/19', '01/06/19',
       '01/05/19', '01/04/19', '01/03/19', '01/02/19', '01/01/19',
       '01/12/18', '01/11/18', '01/10/18', '01/09/18', '01/08/18',
       '01/07/18', '01/06/18', '01/05/18', '01/04/18', '01/03/18',
       '01/02/18', '01/01/18', '01/12/17', '01/11/17', '01/10/17',
       '01/09/17', '01/08/17', '01/07/17', '01/06/17', '01/05/17',
       '01/04/17', '01/03/17', '01/02/17', '01/01/17', '01/12/16',
       '01/11/16', '01/10/16', '01/09/16', '01/08/16', '01/07/16',
       '01/06/16', '01/05/16', '01/04/16', '01/03/16', '01/02/16',
       '01/01/16', '01/12/15', '01/11/15', '01/10/15', '01/09/15',
       '01/08/15', '01/07/15', '01/06/15', '01/05/15', '01/04/15',
       '01/03/15', '01/02/15', '01/01/15', '01/12/14', '01/11/14',
       '01/10/14', '01/09/14', '01/08/14', '01/07/14', '01/06/

In [5]:
tokenizer = tf.keras.preprocessing.text.Tokenizer()
tokenizer.fit_on_sequences(date_array)
tokenizer.fit_on_texts(date_array)

In [6]:
date_array_text = tokenizer.texts_to_sequences(date_array)

In [7]:
date_array_text

[[1, 2, 28],
 [1, 3, 28],
 [1, 4, 28],
 [1, 5, 28],
 [1, 6, 28],
 [1, 7, 28],
 [1, 8, 28],
 [1, 1, 28],
 [1, 9, 13],
 [1, 10, 13],
 [1, 11, 13],
 [1, 12, 13],
 [1, 2, 13],
 [1, 3, 13],
 [1, 4, 13],
 [1, 5, 13],
 [1, 6, 13],
 [1, 7, 13],
 [1, 8, 13],
 [1, 1, 13],
 [1, 9, 14],
 [1, 10, 14],
 [1, 11, 14],
 [1, 12, 14],
 [1, 2, 14],
 [1, 3, 14],
 [1, 4, 14],
 [1, 5, 14],
 [1, 6, 14],
 [1, 7, 14],
 [1, 8, 14],
 [1, 1, 14],
 [1, 9, 15],
 [1, 10, 15],
 [1, 11, 15],
 [1, 12, 15],
 [1, 2, 15],
 [1, 3, 15],
 [1, 4, 15],
 [1, 5, 15],
 [1, 6, 15],
 [1, 7, 15],
 [1, 8, 15],
 [1, 1, 15],
 [1, 9, 16],
 [1, 10, 16],
 [1, 11, 16],
 [1, 12, 16],
 [1, 2, 16],
 [1, 3, 16],
 [1, 4, 16],
 [1, 5, 16],
 [1, 6, 16],
 [1, 7, 16],
 [1, 8, 16],
 [1, 1, 16],
 [1, 9, 17],
 [1, 10, 17],
 [1, 11, 17],
 [1, 12, 17],
 [1, 2, 17],
 [1, 3, 17],
 [1, 4, 17],
 [1, 5, 17],
 [1, 6, 17],
 [1, 7, 17],
 [1, 8, 17],
 [1, 1, 17],
 [1, 9, 18],
 [1, 10, 18],
 [1, 11, 18],
 [1, 12, 18],
 [1, 2, 18],
 [1, 3, 18],
 [1, 4, 18],
 [1, 5,

In [8]:
df_dolar_brl

Date    Last  Opening     Max     Min
0    01/08/20  5.5567   5.2223  5.6722  5.2131
1    01/07/20  5.2242   5.4660  5.4763  5.0827
2    01/06/20  5.4672   5.3340  5.5082  4.8175
3    01/05/20  5.3370   5.4861  5.9718  5.2691
4    01/04/20  5.4875   5.2252  5.7484  5.0487
..        ...     ...      ...     ...     ...
327  01/05/93  0.0152   0.0152  0.0152  0.0152
328  01/04/93  0.0117   0.0117  0.0117  0.0117
329  01/03/93  0.0103   0.0103  0.0103  0.0103
330  01/02/93  0.0079   0.0079  0.0079  0.0079
331  01/01/93  0.0060   0.0060  0.0060  0.0060

[332 rows x 5 columns]

In [9]:
selected_columns = ['Last', 'Opening']
df_dolar_brl = df_dolar_brl[selected_columns]

In [10]:
X_train = np.array(date_array_text)
y_train = df_dolar_brl['Opening']

In [11]:
X_train.shape

(332, 3)

In [12]:
y_train = np.array(y_train)

In [13]:
y_train.shape

(332,)

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
x_scaler = MinMaxScaler()
y_scaler = MinMaxScaler()

In [16]:
X_train = x_scaler.fit_transform(X_train)
y_train = y_scaler.fit_transform(y_train.reshape(-1,1))

In [18]:
X_train

array([[0.        , 0.09090909, 1.        ],
       [0.        , 0.18181818, 1.        ],
       [0.        , 0.27272727, 1.        ],
       [0.        , 0.36363636, 1.        ],
       [0.        , 0.45454545, 1.        ],
       [0.        , 0.54545455, 1.        ],
       [0.        , 0.63636364, 1.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.72727273, 0.44444444],
       [0.        , 0.81818182, 0.44444444],
       [0.        , 0.90909091, 0.44444444],
       [0.        , 1.        , 0.44444444],
       [0.        , 0.09090909, 0.44444444],
       [0.        , 0.18181818, 0.44444444],
       [0.        , 0.27272727, 0.44444444],
       [0.        , 0.36363636, 0.44444444],
       [0.        , 0.45454545, 0.44444444],
       [0.        , 0.54545455, 0.44444444],
       [0.        , 0.63636364, 0.44444444],
       [0.        , 0.        , 0.44444444],
       [0.        , 0.72727273, 0.48148148],
       [0.        , 0.81818182, 0.48148148],
       [0.

In [19]:
y_train

array([[9.51862192e-01],
       [9.96332184e-01],
       [9.72245032e-01],
       [1.00000000e+00],
       [9.52391380e-01],
       [8.19127388e-01],
       [7.80004015e-01],
       [7.32450138e-01],
       [7.71993212e-01],
       [7.32012190e-01],
       [7.57522673e-01],
       [7.55004471e-01],
       [6.95224540e-01],
       [6.99166074e-01],
       [7.14713235e-01],
       [7.14293535e-01],
       [7.08654952e-01],
       [6.83527673e-01],
       [6.64166712e-01],
       [7.06629441e-01],
       [7.04549187e-01],
       [6.78199303e-01],
       [7.37887995e-01],
       [7.45771063e-01],
       [6.84458313e-01],
       [7.06629441e-01],
       [6.78691995e-01],
       [6.39039434e-01],
       [6.02014562e-01],
       [5.91284831e-01],
       [5.80226638e-01],
       [6.03529133e-01],
       [5.96138757e-01],
       [5.96065765e-01],
       [5.76285104e-01],
       [5.73255962e-01],
       [5.69533403e-01],
       [6.04532764e-01],
       [5.87781245e-01],
       [5.78566085e-01],


In [20]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=332, output_dim=32, input_length=3),
    tf.keras.layers.LSTM(units=10),
    tf.keras.layers.Dense(units=1, activation='linear')
])

In [21]:
model.compile(optimizer='Adam', loss='mean_squared_error')

In [22]:
model.fit(X_train, y_train, epochs=500)

Epoch 1/500
11/11 [==============================] - 2s 3ms/step - loss: 0.1616
Epoch 2/500
11/11 [==============================] - 0s 3ms/step - loss: 0.1052
Epoch 3/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0619
Epoch 4/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0392
Epoch 5/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0389
Epoch 6/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0377
Epoch 7/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0370
Epoch 8/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0367
Epoch 9/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0364
Epoch 10/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0361
Epoch 11/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0358
Epoch 12/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0356
Epoch 13/500
11/11 [=================

11/11 [==============================] - 0s 3ms/step - loss: 0.0310
Epoch 103/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 104/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0310
Epoch 105/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 106/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 107/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 108/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0313
Epoch 109/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 110/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 111/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0313
Epoch 112/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 113/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 114/500
11/11 [=========

11/11 [==============================] - 0s 3ms/step - loss: 0.0312
Epoch 203/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0310
Epoch 204/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0312
Epoch 205/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 206/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0309
Epoch 207/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 208/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0310
Epoch 209/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0312
Epoch 210/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 211/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0312
Epoch 212/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0309
Epoch 213/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0310
Epoch 214/500
11/11 [=========

11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 303/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0310
Epoch 304/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0310
Epoch 305/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0313
Epoch 306/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0310
Epoch 307/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 308/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0310
Epoch 309/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0312
Epoch 310/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 311/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0310
Epoch 312/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 313/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0310
Epoch 314/500
11/11 [=========

11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 403/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 404/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0313
Epoch 405/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 406/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0311
Epoch 407/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0310
Epoch 408/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0310
Epoch 409/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0314
Epoch 410/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0310
Epoch 411/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0310
Epoch 412/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0310
Epoch 413/500
11/11 [==============================] - 0s 3ms/step - loss: 0.0310
Epoch 414/500
11/11 [=========

In [31]:
test_date = ['12/08/2023']
tokenizer.fit_on_sequences(test_date)
tokenizer.fit_on_texts(test_date)
test_date = tokenizer.texts_to_sequences(test_date)
test_date_normalized = x_scaler.transform(test_date)
test_date_normalized

array([[8.        , 0.09090909, 1.11111111]])

In [32]:
predict = model.predict(test_date_normalized)

1/1 [==============================] - 0s 19ms/step


In [33]:
predict

array([[0.8174016]], dtype=float32)

In [34]:
predict = predict.reshape(1,-1)

In [35]:
predict

array([[0.8174016]], dtype=float32)

In [36]:
predict_new = y_scaler.inverse_transform(predict)

In [37]:
predict_new

array([[4.4854426]], dtype=float32)

In [41]:
with open('tokenizer.p', 'wb') as filetokenizer:
    pickle.dump(tokenizer, filetokenizer)
    
with open('x_scaler.p', 'wb') as x_fileminmax:
    pickle.dump(x_scaler, x_fileminmax)
    
with open('y_scaler.p', 'wb') as y_fileminmax:
    pickle.dump(y_scaler, y_fileminmax)

model.save("model.h5")